/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-04 at 21:45:47 UTC 
 * Modify at your own risk.
 */

package com.appspot.taxicab_995.vehiculoendpoint;

/**
 * Service definition for Vehiculoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link VehiculoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Vehiculoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the vehiculoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://taxicab-995.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "vehiculoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Vehiculoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Vehiculoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getVehiculo".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link GetVehiculo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetVehiculo getVehiculo(java.lang.Long id) throws java.io.IOException {
    GetVehiculo result = new GetVehiculo(id);
    initialize(result);
    return result;
  }

  public class GetVehiculo extends VehiculoendpointRequest<com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo> {

    private static final String REST_PATH = "vehiculo/{id}";

    /**
     * Create a request for the method "getVehiculo".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link GetVehiculo#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetVehiculo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetVehiculo(java.lang.Long id) {
      super(Vehiculoendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVehiculo setAlt(java.lang.String alt) {
      return (GetVehiculo) super.setAlt(alt);
    }

    @Override
    public GetVehiculo setFields(java.lang.String fields) {
      return (GetVehiculo) super.setFields(fields);
    }

    @Override
    public GetVehiculo setKey(java.lang.String key) {
      return (GetVehiculo) super.setKey(key);
    }

    @Override
    public GetVehiculo setOauthToken(java.lang.String oauthToken) {
      return (GetVehiculo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVehiculo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVehiculo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVehiculo setQuotaUser(java.lang.String quotaUser) {
      return (GetVehiculo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVehiculo setUserIp(java.lang.String userIp) {
      return (GetVehiculo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetVehiculo setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetVehiculo set(String parameterName, Object value) {
      return (GetVehiculo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertVehiculo".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link InsertVehiculo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo}
   * @return the request
   */
  public InsertVehiculo insertVehiculo(com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo content) throws java.io.IOException {
    InsertVehiculo result = new InsertVehiculo(content);
    initialize(result);
    return result;
  }

  public class InsertVehiculo extends VehiculoendpointRequest<com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo> {

    private static final String REST_PATH = "vehiculo";

    /**
     * Create a request for the method "insertVehiculo".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link InsertVehiculo#execute()} method to invoke the remote
     * operation. <p> {@link InsertVehiculo#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo}
     * @since 1.13
     */
    protected InsertVehiculo(com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo content) {
      super(Vehiculoendpoint.this, "POST", REST_PATH, content, com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo.class);
    }

    @Override
    public InsertVehiculo setAlt(java.lang.String alt) {
      return (InsertVehiculo) super.setAlt(alt);
    }

    @Override
    public InsertVehiculo setFields(java.lang.String fields) {
      return (InsertVehiculo) super.setFields(fields);
    }

    @Override
    public InsertVehiculo setKey(java.lang.String key) {
      return (InsertVehiculo) super.setKey(key);
    }

    @Override
    public InsertVehiculo setOauthToken(java.lang.String oauthToken) {
      return (InsertVehiculo) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertVehiculo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertVehiculo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertVehiculo setQuotaUser(java.lang.String quotaUser) {
      return (InsertVehiculo) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertVehiculo setUserIp(java.lang.String userIp) {
      return (InsertVehiculo) super.setUserIp(userIp);
    }

    @Override
    public InsertVehiculo set(String parameterName, Object value) {
      return (InsertVehiculo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMisVehiculos".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link ListMisVehiculos#execute()} method to invoke the remote
   * operation.
   *
   * @param idPropietario
   * @return the request
   */
  public ListMisVehiculos listMisVehiculos(java.lang.String idPropietario) throws java.io.IOException {
    ListMisVehiculos result = new ListMisVehiculos(idPropietario);
    initialize(result);
    return result;
  }

  public class ListMisVehiculos extends VehiculoendpointRequest<com.appspot.taxicab_995.vehiculoendpoint.model.CollectionResponseVehiculo> {

    private static final String REST_PATH = "listmisvehiculos";

    /**
     * Create a request for the method "listMisVehiculos".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link ListMisVehiculos#execute()} method to invoke the remote
     * operation. <p> {@link ListMisVehiculos#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param idPropietario
     * @since 1.13
     */
    protected ListMisVehiculos(java.lang.String idPropietario) {
      super(Vehiculoendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.vehiculoendpoint.model.CollectionResponseVehiculo.class);
      this.idPropietario = com.google.api.client.util.Preconditions.checkNotNull(idPropietario, "Required parameter idPropietario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMisVehiculos setAlt(java.lang.String alt) {
      return (ListMisVehiculos) super.setAlt(alt);
    }

    @Override
    public ListMisVehiculos setFields(java.lang.String fields) {
      return (ListMisVehiculos) super.setFields(fields);
    }

    @Override
    public ListMisVehiculos setKey(java.lang.String key) {
      return (ListMisVehiculos) super.setKey(key);
    }

    @Override
    public ListMisVehiculos setOauthToken(java.lang.String oauthToken) {
      return (ListMisVehiculos) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMisVehiculos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMisVehiculos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMisVehiculos setQuotaUser(java.lang.String quotaUser) {
      return (ListMisVehiculos) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMisVehiculos setUserIp(java.lang.String userIp) {
      return (ListMisVehiculos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String idPropietario;

    /**

     */
    public java.lang.String getIdPropietario() {
      return idPropietario;
    }

    public ListMisVehiculos setIdPropietario(java.lang.String idPropietario) {
      this.idPropietario = idPropietario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMisVehiculos setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMisVehiculos setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMisVehiculos set(String parameterName, Object value) {
      return (ListMisVehiculos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTodosVehiculos".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link ListTodosVehiculos#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTodosVehiculos listTodosVehiculos() throws java.io.IOException {
    ListTodosVehiculos result = new ListTodosVehiculos();
    initialize(result);
    return result;
  }

  public class ListTodosVehiculos extends VehiculoendpointRequest<com.appspot.taxicab_995.vehiculoendpoint.model.CollectionResponseVehiculo> {

    private static final String REST_PATH = "listtodosvehiculos";

    /**
     * Create a request for the method "listTodosVehiculos".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link ListTodosVehiculos#execute()} method to invoke the remote
     * operation. <p> {@link ListTodosVehiculos#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTodosVehiculos() {
      super(Vehiculoendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.vehiculoendpoint.model.CollectionResponseVehiculo.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTodosVehiculos setAlt(java.lang.String alt) {
      return (ListTodosVehiculos) super.setAlt(alt);
    }

    @Override
    public ListTodosVehiculos setFields(java.lang.String fields) {
      return (ListTodosVehiculos) super.setFields(fields);
    }

    @Override
    public ListTodosVehiculos setKey(java.lang.String key) {
      return (ListTodosVehiculos) super.setKey(key);
    }

    @Override
    public ListTodosVehiculos setOauthToken(java.lang.String oauthToken) {
      return (ListTodosVehiculos) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTodosVehiculos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTodosVehiculos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTodosVehiculos setQuotaUser(java.lang.String quotaUser) {
      return (ListTodosVehiculos) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTodosVehiculos setUserIp(java.lang.String userIp) {
      return (ListTodosVehiculos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTodosVehiculos setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTodosVehiculos setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTodosVehiculos set(String parameterName, Object value) {
      return (ListTodosVehiculos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "toggleVehiculo".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link ToggleVehiculo#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public ToggleVehiculo toggleVehiculo(java.lang.String id) throws java.io.IOException {
    ToggleVehiculo result = new ToggleVehiculo(id);
    initialize(result);
    return result;
  }

  public class ToggleVehiculo extends VehiculoendpointRequest<Void> {

    private static final String REST_PATH = "vehiculo/{id}";

    /**
     * Create a request for the method "toggleVehiculo".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link ToggleVehiculo#execute()} method to invoke the remote
     * operation. <p> {@link ToggleVehiculo#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected ToggleVehiculo(java.lang.String id) {
      super(Vehiculoendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public ToggleVehiculo setAlt(java.lang.String alt) {
      return (ToggleVehiculo) super.setAlt(alt);
    }

    @Override
    public ToggleVehiculo setFields(java.lang.String fields) {
      return (ToggleVehiculo) super.setFields(fields);
    }

    @Override
    public ToggleVehiculo setKey(java.lang.String key) {
      return (ToggleVehiculo) super.setKey(key);
    }

    @Override
    public ToggleVehiculo setOauthToken(java.lang.String oauthToken) {
      return (ToggleVehiculo) super.setOauthToken(oauthToken);
    }

    @Override
    public ToggleVehiculo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ToggleVehiculo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ToggleVehiculo setQuotaUser(java.lang.String quotaUser) {
      return (ToggleVehiculo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ToggleVehiculo setUserIp(java.lang.String userIp) {
      return (ToggleVehiculo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public ToggleVehiculo setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public ToggleVehiculo set(String parameterName, Object value) {
      return (ToggleVehiculo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateEstadoVehiculo".
   *
   * This request holds the parameters needed by the vehiculoendpoint server.  After setting any
   * optional parameters, call the {@link UpdateEstadoVehiculo#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo}
   * @return the request
   */
  public UpdateEstadoVehiculo updateEstadoVehiculo(com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo content) throws java.io.IOException {
    UpdateEstadoVehiculo result = new UpdateEstadoVehiculo(content);
    initialize(result);
    return result;
  }

  public class UpdateEstadoVehiculo extends VehiculoendpointRequest<com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo> {

    private static final String REST_PATH = "updateestadovehiculo";

    /**
     * Create a request for the method "updateEstadoVehiculo".
     *
     * This request holds the parameters needed by the the vehiculoendpoint server.  After setting any
     * optional parameters, call the {@link UpdateEstadoVehiculo#execute()} method to invoke the
     * remote operation. <p> {@link UpdateEstadoVehiculo#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo}
     * @since 1.13
     */
    protected UpdateEstadoVehiculo(com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo content) {
      super(Vehiculoendpoint.this, "PUT", REST_PATH, content, com.appspot.taxicab_995.vehiculoendpoint.model.Vehiculo.class);
    }

    @Override
    public UpdateEstadoVehiculo setAlt(java.lang.String alt) {
      return (UpdateEstadoVehiculo) super.setAlt(alt);
    }

    @Override
    public UpdateEstadoVehiculo setFields(java.lang.String fields) {
      return (UpdateEstadoVehiculo) super.setFields(fields);
    }

    @Override
    public UpdateEstadoVehiculo setKey(java.lang.String key) {
      return (UpdateEstadoVehiculo) super.setKey(key);
    }

    @Override
    public UpdateEstadoVehiculo setOauthToken(java.lang.String oauthToken) {
      return (UpdateEstadoVehiculo) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateEstadoVehiculo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateEstadoVehiculo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateEstadoVehiculo setQuotaUser(java.lang.String quotaUser) {
      return (UpdateEstadoVehiculo) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateEstadoVehiculo setUserIp(java.lang.String userIp) {
      return (UpdateEstadoVehiculo) super.setUserIp(userIp);
    }

    @Override
    public UpdateEstadoVehiculo set(String parameterName, Object value) {
      return (UpdateEstadoVehiculo) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Vehiculoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Vehiculoendpoint}. */
    @Override
    public Vehiculoendpoint build() {
      return new Vehiculoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link VehiculoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setVehiculoendpointRequestInitializer(
        VehiculoendpointRequestInitializer vehiculoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(vehiculoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
