/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-04 at 21:45:13 UTC 
 * Modify at your own risk.
 */

package com.appspot.taxicab_995.propietarioendpoint;

/**
 * Service definition for Propietarioendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PropietarioendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Propietarioendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the propietarioendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://taxicab-995.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "propietarioendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Propietarioendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Propietarioendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPropietario".
   *
   * This request holds the parameters needed by the propietarioendpoint server.  After setting any
   * optional parameters, call the {@link GetPropietario#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPropietario getPropietario(java.lang.Long id) throws java.io.IOException {
    GetPropietario result = new GetPropietario(id);
    initialize(result);
    return result;
  }

  public class GetPropietario extends PropietarioendpointRequest<com.appspot.taxicab_995.propietarioendpoint.model.Propietario> {

    private static final String REST_PATH = "propietario/{id}";

    /**
     * Create a request for the method "getPropietario".
     *
     * This request holds the parameters needed by the the propietarioendpoint server.  After setting
     * any optional parameters, call the {@link GetPropietario#execute()} method to invoke the remote
     * operation. <p> {@link GetPropietario#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPropietario(java.lang.Long id) {
      super(Propietarioendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.propietarioendpoint.model.Propietario.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPropietario setAlt(java.lang.String alt) {
      return (GetPropietario) super.setAlt(alt);
    }

    @Override
    public GetPropietario setFields(java.lang.String fields) {
      return (GetPropietario) super.setFields(fields);
    }

    @Override
    public GetPropietario setKey(java.lang.String key) {
      return (GetPropietario) super.setKey(key);
    }

    @Override
    public GetPropietario setOauthToken(java.lang.String oauthToken) {
      return (GetPropietario) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPropietario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPropietario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPropietario setQuotaUser(java.lang.String quotaUser) {
      return (GetPropietario) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPropietario setUserIp(java.lang.String userIp) {
      return (GetPropietario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPropietario setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPropietario set(String parameterName, Object value) {
      return (GetPropietario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPropietario".
   *
   * This request holds the parameters needed by the propietarioendpoint server.  After setting any
   * optional parameters, call the {@link InsertPropietario#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.propietarioendpoint.model.Propietario}
   * @return the request
   */
  public InsertPropietario insertPropietario(com.appspot.taxicab_995.propietarioendpoint.model.Propietario content) throws java.io.IOException {
    InsertPropietario result = new InsertPropietario(content);
    initialize(result);
    return result;
  }

  public class InsertPropietario extends PropietarioendpointRequest<com.appspot.taxicab_995.propietarioendpoint.model.Propietario> {

    private static final String REST_PATH = "propietario";

    /**
     * Create a request for the method "insertPropietario".
     *
     * This request holds the parameters needed by the the propietarioendpoint server.  After setting
     * any optional parameters, call the {@link InsertPropietario#execute()} method to invoke the
     * remote operation. <p> {@link InsertPropietario#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.propietarioendpoint.model.Propietario}
     * @since 1.13
     */
    protected InsertPropietario(com.appspot.taxicab_995.propietarioendpoint.model.Propietario content) {
      super(Propietarioendpoint.this, "POST", REST_PATH, content, com.appspot.taxicab_995.propietarioendpoint.model.Propietario.class);
    }

    @Override
    public InsertPropietario setAlt(java.lang.String alt) {
      return (InsertPropietario) super.setAlt(alt);
    }

    @Override
    public InsertPropietario setFields(java.lang.String fields) {
      return (InsertPropietario) super.setFields(fields);
    }

    @Override
    public InsertPropietario setKey(java.lang.String key) {
      return (InsertPropietario) super.setKey(key);
    }

    @Override
    public InsertPropietario setOauthToken(java.lang.String oauthToken) {
      return (InsertPropietario) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPropietario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPropietario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPropietario setQuotaUser(java.lang.String quotaUser) {
      return (InsertPropietario) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPropietario setUserIp(java.lang.String userIp) {
      return (InsertPropietario) super.setUserIp(userIp);
    }

    @Override
    public InsertPropietario set(String parameterName, Object value) {
      return (InsertPropietario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPropietario".
   *
   * This request holds the parameters needed by the propietarioendpoint server.  After setting any
   * optional parameters, call the {@link ListPropietario#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPropietario listPropietario() throws java.io.IOException {
    ListPropietario result = new ListPropietario();
    initialize(result);
    return result;
  }

  public class ListPropietario extends PropietarioendpointRequest<com.appspot.taxicab_995.propietarioendpoint.model.CollectionResponsePropietario> {

    private static final String REST_PATH = "propietario";

    /**
     * Create a request for the method "listPropietario".
     *
     * This request holds the parameters needed by the the propietarioendpoint server.  After setting
     * any optional parameters, call the {@link ListPropietario#execute()} method to invoke the remote
     * operation. <p> {@link ListPropietario#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPropietario() {
      super(Propietarioendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.propietarioendpoint.model.CollectionResponsePropietario.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPropietario setAlt(java.lang.String alt) {
      return (ListPropietario) super.setAlt(alt);
    }

    @Override
    public ListPropietario setFields(java.lang.String fields) {
      return (ListPropietario) super.setFields(fields);
    }

    @Override
    public ListPropietario setKey(java.lang.String key) {
      return (ListPropietario) super.setKey(key);
    }

    @Override
    public ListPropietario setOauthToken(java.lang.String oauthToken) {
      return (ListPropietario) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPropietario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPropietario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPropietario setQuotaUser(java.lang.String quotaUser) {
      return (ListPropietario) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPropietario setUserIp(java.lang.String userIp) {
      return (ListPropietario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPropietario setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPropietario setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPropietario set(String parameterName, Object value) {
      return (ListPropietario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "togglePropietario".
   *
   * This request holds the parameters needed by the propietarioendpoint server.  After setting any
   * optional parameters, call the {@link TogglePropietario#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public TogglePropietario togglePropietario(java.lang.String id) throws java.io.IOException {
    TogglePropietario result = new TogglePropietario(id);
    initialize(result);
    return result;
  }

  public class TogglePropietario extends PropietarioendpointRequest<Void> {

    private static final String REST_PATH = "propietario/{id}";

    /**
     * Create a request for the method "togglePropietario".
     *
     * This request holds the parameters needed by the the propietarioendpoint server.  After setting
     * any optional parameters, call the {@link TogglePropietario#execute()} method to invoke the
     * remote operation. <p> {@link TogglePropietario#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected TogglePropietario(java.lang.String id) {
      super(Propietarioendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public TogglePropietario setAlt(java.lang.String alt) {
      return (TogglePropietario) super.setAlt(alt);
    }

    @Override
    public TogglePropietario setFields(java.lang.String fields) {
      return (TogglePropietario) super.setFields(fields);
    }

    @Override
    public TogglePropietario setKey(java.lang.String key) {
      return (TogglePropietario) super.setKey(key);
    }

    @Override
    public TogglePropietario setOauthToken(java.lang.String oauthToken) {
      return (TogglePropietario) super.setOauthToken(oauthToken);
    }

    @Override
    public TogglePropietario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (TogglePropietario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public TogglePropietario setQuotaUser(java.lang.String quotaUser) {
      return (TogglePropietario) super.setQuotaUser(quotaUser);
    }

    @Override
    public TogglePropietario setUserIp(java.lang.String userIp) {
      return (TogglePropietario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public TogglePropietario setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public TogglePropietario set(String parameterName, Object value) {
      return (TogglePropietario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePropietario".
   *
   * This request holds the parameters needed by the propietarioendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePropietario#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.propietarioendpoint.model.Propietario}
   * @return the request
   */
  public UpdatePropietario updatePropietario(com.appspot.taxicab_995.propietarioendpoint.model.Propietario content) throws java.io.IOException {
    UpdatePropietario result = new UpdatePropietario(content);
    initialize(result);
    return result;
  }

  public class UpdatePropietario extends PropietarioendpointRequest<com.appspot.taxicab_995.propietarioendpoint.model.Propietario> {

    private static final String REST_PATH = "propietario";

    /**
     * Create a request for the method "updatePropietario".
     *
     * This request holds the parameters needed by the the propietarioendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePropietario#execute()} method to invoke the
     * remote operation. <p> {@link UpdatePropietario#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.propietarioendpoint.model.Propietario}
     * @since 1.13
     */
    protected UpdatePropietario(com.appspot.taxicab_995.propietarioendpoint.model.Propietario content) {
      super(Propietarioendpoint.this, "PUT", REST_PATH, content, com.appspot.taxicab_995.propietarioendpoint.model.Propietario.class);
    }

    @Override
    public UpdatePropietario setAlt(java.lang.String alt) {
      return (UpdatePropietario) super.setAlt(alt);
    }

    @Override
    public UpdatePropietario setFields(java.lang.String fields) {
      return (UpdatePropietario) super.setFields(fields);
    }

    @Override
    public UpdatePropietario setKey(java.lang.String key) {
      return (UpdatePropietario) super.setKey(key);
    }

    @Override
    public UpdatePropietario setOauthToken(java.lang.String oauthToken) {
      return (UpdatePropietario) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePropietario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePropietario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePropietario setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePropietario) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePropietario setUserIp(java.lang.String userIp) {
      return (UpdatePropietario) super.setUserIp(userIp);
    }

    @Override
    public UpdatePropietario set(String parameterName, Object value) {
      return (UpdatePropietario) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Propietarioendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Propietarioendpoint}. */
    @Override
    public Propietarioendpoint build() {
      return new Propietarioendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PropietarioendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPropietarioendpointRequestInitializer(
        PropietarioendpointRequestInitializer propietarioendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(propietarioendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
