/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-04 at 21:44:31 UTC 
 * Modify at your own risk.
 */

package com.appspot.taxicab_995.conductorendpoint;

/**
 * Service definition for Conductorendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ConductorendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Conductorendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the conductorendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://taxicab-995.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "conductorendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Conductorendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Conductorendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link GetConductor#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetConductor getConductor(java.lang.Long id) throws java.io.IOException {
    GetConductor result = new GetConductor(id);
    initialize(result);
    return result;
  }

  public class GetConductor extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.Conductor> {

    private static final String REST_PATH = "conductor/{id}";

    /**
     * Create a request for the method "getConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link GetConductor#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetConductor#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetConductor(java.lang.Long id) {
      super(Conductorendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.conductorendpoint.model.Conductor.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetConductor setAlt(java.lang.String alt) {
      return (GetConductor) super.setAlt(alt);
    }

    @Override
    public GetConductor setFields(java.lang.String fields) {
      return (GetConductor) super.setFields(fields);
    }

    @Override
    public GetConductor setKey(java.lang.String key) {
      return (GetConductor) super.setKey(key);
    }

    @Override
    public GetConductor setOauthToken(java.lang.String oauthToken) {
      return (GetConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public GetConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetConductor setQuotaUser(java.lang.String quotaUser) {
      return (GetConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetConductor setUserIp(java.lang.String userIp) {
      return (GetConductor) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetConductor setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetConductor set(String parameterName, Object value) {
      return (GetConductor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link InsertConductor#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
   * @return the request
   */
  public InsertConductor insertConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) throws java.io.IOException {
    InsertConductor result = new InsertConductor(content);
    initialize(result);
    return result;
  }

  public class InsertConductor extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.Conductor> {

    private static final String REST_PATH = "conductor";

    /**
     * Create a request for the method "insertConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link InsertConductor#execute()} method to invoke the remote
     * operation. <p> {@link InsertConductor#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
     * @since 1.13
     */
    protected InsertConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) {
      super(Conductorendpoint.this, "POST", REST_PATH, content, com.appspot.taxicab_995.conductorendpoint.model.Conductor.class);
    }

    @Override
    public InsertConductor setAlt(java.lang.String alt) {
      return (InsertConductor) super.setAlt(alt);
    }

    @Override
    public InsertConductor setFields(java.lang.String fields) {
      return (InsertConductor) super.setFields(fields);
    }

    @Override
    public InsertConductor setKey(java.lang.String key) {
      return (InsertConductor) super.setKey(key);
    }

    @Override
    public InsertConductor setOauthToken(java.lang.String oauthToken) {
      return (InsertConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertConductor setQuotaUser(java.lang.String quotaUser) {
      return (InsertConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertConductor setUserIp(java.lang.String userIp) {
      return (InsertConductor) super.setUserIp(userIp);
    }

    @Override
    public InsertConductor set(String parameterName, Object value) {
      return (InsertConductor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listConductoresVehiculo".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link ListConductoresVehiculo#execute()} method to invoke the
   * remote operation.
   *
   * @param idPropietario
   * @param placa
   * @return the request
   */
  public ListConductoresVehiculo listConductoresVehiculo(java.lang.String idPropietario, java.lang.String placa) throws java.io.IOException {
    ListConductoresVehiculo result = new ListConductoresVehiculo(idPropietario, placa);
    initialize(result);
    return result;
  }

  public class ListConductoresVehiculo extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor> {

    private static final String REST_PATH = "conductor/{idPropietario}/{placa}";

    /**
     * Create a request for the method "listConductoresVehiculo".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link ListConductoresVehiculo#execute()} method to invoke
     * the remote operation. <p> {@link ListConductoresVehiculo#initialize(com.google.api.client.googl
     * eapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param idPropietario
     * @param placa
     * @since 1.13
     */
    protected ListConductoresVehiculo(java.lang.String idPropietario, java.lang.String placa) {
      super(Conductorendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor.class);
      this.idPropietario = com.google.api.client.util.Preconditions.checkNotNull(idPropietario, "Required parameter idPropietario must be specified.");
      this.placa = com.google.api.client.util.Preconditions.checkNotNull(placa, "Required parameter placa must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListConductoresVehiculo setAlt(java.lang.String alt) {
      return (ListConductoresVehiculo) super.setAlt(alt);
    }

    @Override
    public ListConductoresVehiculo setFields(java.lang.String fields) {
      return (ListConductoresVehiculo) super.setFields(fields);
    }

    @Override
    public ListConductoresVehiculo setKey(java.lang.String key) {
      return (ListConductoresVehiculo) super.setKey(key);
    }

    @Override
    public ListConductoresVehiculo setOauthToken(java.lang.String oauthToken) {
      return (ListConductoresVehiculo) super.setOauthToken(oauthToken);
    }

    @Override
    public ListConductoresVehiculo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListConductoresVehiculo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListConductoresVehiculo setQuotaUser(java.lang.String quotaUser) {
      return (ListConductoresVehiculo) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListConductoresVehiculo setUserIp(java.lang.String userIp) {
      return (ListConductoresVehiculo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String idPropietario;

    /**

     */
    public java.lang.String getIdPropietario() {
      return idPropietario;
    }

    public ListConductoresVehiculo setIdPropietario(java.lang.String idPropietario) {
      this.idPropietario = idPropietario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String placa;

    /**

     */
    public java.lang.String getPlaca() {
      return placa;
    }

    public ListConductoresVehiculo setPlaca(java.lang.String placa) {
      this.placa = placa;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListConductoresVehiculo setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListConductoresVehiculo setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListConductoresVehiculo set(String parameterName, Object value) {
      return (ListConductoresVehiculo) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTodosConductores".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link ListTodosConductores#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTodosConductores listTodosConductores() throws java.io.IOException {
    ListTodosConductores result = new ListTodosConductores();
    initialize(result);
    return result;
  }

  public class ListTodosConductores extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor> {

    private static final String REST_PATH = "listtodosconductores";

    /**
     * Create a request for the method "listTodosConductores".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link ListTodosConductores#execute()} method to invoke the
     * remote operation. <p> {@link ListTodosConductores#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTodosConductores() {
      super(Conductorendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTodosConductores setAlt(java.lang.String alt) {
      return (ListTodosConductores) super.setAlt(alt);
    }

    @Override
    public ListTodosConductores setFields(java.lang.String fields) {
      return (ListTodosConductores) super.setFields(fields);
    }

    @Override
    public ListTodosConductores setKey(java.lang.String key) {
      return (ListTodosConductores) super.setKey(key);
    }

    @Override
    public ListTodosConductores setOauthToken(java.lang.String oauthToken) {
      return (ListTodosConductores) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTodosConductores setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTodosConductores) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTodosConductores setQuotaUser(java.lang.String quotaUser) {
      return (ListTodosConductores) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTodosConductores setUserIp(java.lang.String userIp) {
      return (ListTodosConductores) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTodosConductores setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTodosConductores setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTodosConductores set(String parameterName, Object value) {
      return (ListTodosConductores) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listVehiculosConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link ListVehiculosConductor#execute()} method to invoke the
   * remote operation.
   *
   * @param email
   * @return the request
   */
  public ListVehiculosConductor listVehiculosConductor(java.lang.String email) throws java.io.IOException {
    ListVehiculosConductor result = new ListVehiculosConductor(email);
    initialize(result);
    return result;
  }

  public class ListVehiculosConductor extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor> {

    private static final String REST_PATH = "listvehiculosconductor";

    /**
     * Create a request for the method "listVehiculosConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link ListVehiculosConductor#execute()} method to invoke the
     * remote operation. <p> {@link ListVehiculosConductor#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected ListVehiculosConductor(java.lang.String email) {
      super(Conductorendpoint.this, "GET", REST_PATH, null, com.appspot.taxicab_995.conductorendpoint.model.CollectionResponseConductor.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListVehiculosConductor setAlt(java.lang.String alt) {
      return (ListVehiculosConductor) super.setAlt(alt);
    }

    @Override
    public ListVehiculosConductor setFields(java.lang.String fields) {
      return (ListVehiculosConductor) super.setFields(fields);
    }

    @Override
    public ListVehiculosConductor setKey(java.lang.String key) {
      return (ListVehiculosConductor) super.setKey(key);
    }

    @Override
    public ListVehiculosConductor setOauthToken(java.lang.String oauthToken) {
      return (ListVehiculosConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public ListVehiculosConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListVehiculosConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListVehiculosConductor setQuotaUser(java.lang.String quotaUser) {
      return (ListVehiculosConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListVehiculosConductor setUserIp(java.lang.String userIp) {
      return (ListVehiculosConductor) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public ListVehiculosConductor setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListVehiculosConductor setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListVehiculosConductor setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListVehiculosConductor set(String parameterName, Object value) {
      return (ListVehiculosConductor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "toggleConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link ToggleConductor#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public ToggleConductor toggleConductor(java.lang.String id) throws java.io.IOException {
    ToggleConductor result = new ToggleConductor(id);
    initialize(result);
    return result;
  }

  public class ToggleConductor extends ConductorendpointRequest<Void> {

    private static final String REST_PATH = "conductor/{id}";

    /**
     * Create a request for the method "toggleConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link ToggleConductor#execute()} method to invoke the remote
     * operation. <p> {@link ToggleConductor#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected ToggleConductor(java.lang.String id) {
      super(Conductorendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public ToggleConductor setAlt(java.lang.String alt) {
      return (ToggleConductor) super.setAlt(alt);
    }

    @Override
    public ToggleConductor setFields(java.lang.String fields) {
      return (ToggleConductor) super.setFields(fields);
    }

    @Override
    public ToggleConductor setKey(java.lang.String key) {
      return (ToggleConductor) super.setKey(key);
    }

    @Override
    public ToggleConductor setOauthToken(java.lang.String oauthToken) {
      return (ToggleConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public ToggleConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ToggleConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ToggleConductor setQuotaUser(java.lang.String quotaUser) {
      return (ToggleConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public ToggleConductor setUserIp(java.lang.String userIp) {
      return (ToggleConductor) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public ToggleConductor setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public ToggleConductor set(String parameterName, Object value) {
      return (ToggleConductor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateDocumentosConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link UpdateDocumentosConductor#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
   * @return the request
   */
  public UpdateDocumentosConductor updateDocumentosConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) throws java.io.IOException {
    UpdateDocumentosConductor result = new UpdateDocumentosConductor(content);
    initialize(result);
    return result;
  }

  public class UpdateDocumentosConductor extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.Conductor> {

    private static final String REST_PATH = "updatedocumentosconductor";

    /**
     * Create a request for the method "updateDocumentosConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link UpdateDocumentosConductor#execute()} method to invoke
     * the remote operation. <p> {@link UpdateDocumentosConductor#initialize(com.google.api.client.goo
     * gleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
     * @since 1.13
     */
    protected UpdateDocumentosConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) {
      super(Conductorendpoint.this, "PUT", REST_PATH, content, com.appspot.taxicab_995.conductorendpoint.model.Conductor.class);
    }

    @Override
    public UpdateDocumentosConductor setAlt(java.lang.String alt) {
      return (UpdateDocumentosConductor) super.setAlt(alt);
    }

    @Override
    public UpdateDocumentosConductor setFields(java.lang.String fields) {
      return (UpdateDocumentosConductor) super.setFields(fields);
    }

    @Override
    public UpdateDocumentosConductor setKey(java.lang.String key) {
      return (UpdateDocumentosConductor) super.setKey(key);
    }

    @Override
    public UpdateDocumentosConductor setOauthToken(java.lang.String oauthToken) {
      return (UpdateDocumentosConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateDocumentosConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateDocumentosConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateDocumentosConductor setQuotaUser(java.lang.String quotaUser) {
      return (UpdateDocumentosConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateDocumentosConductor setUserIp(java.lang.String userIp) {
      return (UpdateDocumentosConductor) super.setUserIp(userIp);
    }

    @Override
    public UpdateDocumentosConductor set(String parameterName, Object value) {
      return (UpdateDocumentosConductor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateEstadoConductor".
   *
   * This request holds the parameters needed by the conductorendpoint server.  After setting any
   * optional parameters, call the {@link UpdateEstadoConductor#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
   * @return the request
   */
  public UpdateEstadoConductor updateEstadoConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) throws java.io.IOException {
    UpdateEstadoConductor result = new UpdateEstadoConductor(content);
    initialize(result);
    return result;
  }

  public class UpdateEstadoConductor extends ConductorendpointRequest<com.appspot.taxicab_995.conductorendpoint.model.Conductor> {

    private static final String REST_PATH = "updateestadoconductor";

    /**
     * Create a request for the method "updateEstadoConductor".
     *
     * This request holds the parameters needed by the the conductorendpoint server.  After setting
     * any optional parameters, call the {@link UpdateEstadoConductor#execute()} method to invoke the
     * remote operation. <p> {@link UpdateEstadoConductor#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.taxicab_995.conductorendpoint.model.Conductor}
     * @since 1.13
     */
    protected UpdateEstadoConductor(com.appspot.taxicab_995.conductorendpoint.model.Conductor content) {
      super(Conductorendpoint.this, "PUT", REST_PATH, content, com.appspot.taxicab_995.conductorendpoint.model.Conductor.class);
    }

    @Override
    public UpdateEstadoConductor setAlt(java.lang.String alt) {
      return (UpdateEstadoConductor) super.setAlt(alt);
    }

    @Override
    public UpdateEstadoConductor setFields(java.lang.String fields) {
      return (UpdateEstadoConductor) super.setFields(fields);
    }

    @Override
    public UpdateEstadoConductor setKey(java.lang.String key) {
      return (UpdateEstadoConductor) super.setKey(key);
    }

    @Override
    public UpdateEstadoConductor setOauthToken(java.lang.String oauthToken) {
      return (UpdateEstadoConductor) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateEstadoConductor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateEstadoConductor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateEstadoConductor setQuotaUser(java.lang.String quotaUser) {
      return (UpdateEstadoConductor) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateEstadoConductor setUserIp(java.lang.String userIp) {
      return (UpdateEstadoConductor) super.setUserIp(userIp);
    }

    @Override
    public UpdateEstadoConductor set(String parameterName, Object value) {
      return (UpdateEstadoConductor) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Conductorendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Conductorendpoint}. */
    @Override
    public Conductorendpoint build() {
      return new Conductorendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ConductorendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setConductorendpointRequestInitializer(
        ConductorendpointRequestInitializer conductorendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(conductorendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
