/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-04 at 21:45:47 UTC 
 * Modify at your own risk.
 */

package com.appspot.taxicab_995.vehiculoendpoint.model;

/**
 * Model definition for Vehiculo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the vehiculoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Vehiculo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Documento> documentos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String idPropietario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String marca;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer modelo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String placa;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Documento> getDocumentos() {
    return documentos;
  }

  /**
   * @param documentos documentos or {@code null} for none
   */
  public Vehiculo setDocumentos(java.util.List<Documento> documentos) {
    this.documentos = documentos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public Vehiculo setEstado(java.lang.String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Vehiculo setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdPropietario() {
    return idPropietario;
  }

  /**
   * @param idPropietario idPropietario or {@code null} for none
   */
  public Vehiculo setIdPropietario(java.lang.String idPropietario) {
    this.idPropietario = idPropietario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMarca() {
    return marca;
  }

  /**
   * @param marca marca or {@code null} for none
   */
  public Vehiculo setMarca(java.lang.String marca) {
    this.marca = marca;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getModelo() {
    return modelo;
  }

  /**
   * @param modelo modelo or {@code null} for none
   */
  public Vehiculo setModelo(java.lang.Integer modelo) {
    this.modelo = modelo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPlaca() {
    return placa;
  }

  /**
   * @param placa placa or {@code null} for none
   */
  public Vehiculo setPlaca(java.lang.String placa) {
    this.placa = placa;
    return this;
  }

  @Override
  public Vehiculo set(String fieldName, Object value) {
    return (Vehiculo) super.set(fieldName, value);
  }

  @Override
  public Vehiculo clone() {
    return (Vehiculo) super.clone();
  }

}
